# Pandas and Numpy         
**Thursday, 1 December 2022**
# Pandas

In [1]:
import pandas as pd
pd.DataFrame({ 'col1' : [1,2,3,4,5],
              'col2' : [34,4,234,234,244],
              'col3' : 'Sharad Pardhe IIT MANDI T20071 '
    
})

col1  col2                             col3
0     1    34  Sharad Pardhe IIT MANDI T20071 
1     2     4  Sharad Pardhe IIT MANDI T20071 
2     3   234  Sharad Pardhe IIT MANDI T20071 
3     4   234  Sharad Pardhe IIT MANDI T20071 
4     5   244  Sharad Pardhe IIT MANDI T20071

In [2]:
'Sharad Pardhe IIT MANDI T20071'.split()

['Sharad', 'Pardhe', 'IIT', 'MANDI', 'T20071']

In [3]:
df = pd.DataFrame({ 'col1' : [1,2,3,4,5],
              'col2' : [34,4,234,234,244],
              'col3' : 'Sharad Pardhe IIT MANDI T20071'.split()
    
                   })
df

col1  col2    col3
0     1    34  Sharad
1     2     4  Pardhe
2     3   234     IIT
3     4   234   MANDI
4     5   244  T20071

In [4]:
# new col4 which store square of col1
df['col4'] = df['col1'] **2
df

col1  col2    col3  col4
0     1    34  Sharad     1
1     2     4  Pardhe     4
2     3   234     IIT     9
3     4   234   MANDI    16
4     5   244  T20071    25

In [5]:
# create new col5 which store first latter of col3
df['col5'] = df['col3'].str[0]
df

col1  col2    col3  col4 col5
0     1    34  Sharad     1    S
1     2     4  Pardhe     4    P
2     3   234     IIT     9    I
3     4   234   MANDI    16    M
4     5   244  T20071    25    T

In [6]:
# new col4_4 which store square of col1
# with apply function
def test(a):
    return a**2

df['col4_4'] = df['col1'].apply(test)

In [7]:
df

col1  col2    col3  col4 col5  col4_4
0     1    34  Sharad     1    S       1
1     2     4  Pardhe     4    P       4
2     3   234     IIT     9    I       9
3     4   234   MANDI    16    M      16
4     5   244  T20071    25    T      25

In [8]:
# create new col6, which store col5 if element is s otherwise store z 
def test1(a):
    if a == 'S':
        return 'S'
    else:
        return 'Z'
    
df['col6'] = df['col5'].apply(test1)

In [9]:
df

col1  col2    col3  col4 col5  col4_4 col6
0     1    34  Sharad     1    S       1    S
1     2     4  Pardhe     4    P       4    Z
2     3   234     IIT     9    I       9    Z
3     4   234   MANDI    16    M      16    Z
4     5   244  T20071    25    T      25    Z

In [10]:
# Now, with lambda function
df['col6_6'] = df['col5'].apply(lambda a: 'S' if a == 'S' else 'Z')
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6
0     1    34  Sharad     1    S       1    S      S
1     2     4  Pardhe     4    P       4    Z      Z
2     3   234     IIT     9    I       9    Z      Z
3     4   234   MANDI    16    M      16    Z      Z
4     5   244  T20071    25    T      25    Z      Z

###### apply function is approx same as map in python but apply in it Pandas

In [11]:
# create new col7, which store len of string available in col3
df['col7'] = df['col3'].apply(lambda x:len(x))

In [12]:
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7
0     1    34  Sharad     1    S       1    S      S     6
1     2     4  Pardhe     4    P       4    Z      Z     6
2     3   234     IIT     9    I       9    Z      Z     3
3     4   234   MANDI    16    M      16    Z      Z     5
4     5   244  T20071    25    T      25    Z      Z     6

In [13]:
# 2nd solution 
df['col7_7'] = df['col3'].apply(len)
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7
0     1    34  Sharad     1    S       1    S      S     6       6
1     2     4  Pardhe     4    P       4    Z      Z     6       6
2     3   234     IIT     9    I       9    Z      Z     3       3
3     4   234   MANDI    16    M      16    Z      Z     5       5
4     5   244  T20071    25    T      25    Z      Z     6       6

In [14]:
# create new col8 which store log of col2
import math
df['col8'] = df['col2'].apply(lambda a: math.log(a))
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7      col8
0     1    34  Sharad     1    S       1    S      S     6       6  3.526361
1     2     4  Pardhe     4    P       4    Z      Z     6       6  1.386294
2     3   234     IIT     9    I       9    Z      Z     3       3  5.455321
3     4   234   MANDI    16    M      16    Z      Z     5       5  5.455321
4     5   244  T20071    25    T      25    Z      Z     6       6  5.497168

In [15]:
# 2nd solution 
df['col8_8'] = df['col2'].apply(math.log)
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7      col8  \
0     1    34  Sharad     1    S       1    S      S     6       6  3.526361   
1     2     4  Pardhe     4    P       4    Z      Z     6       6  1.386294   
2     3   234     IIT     9    I       9    Z      Z     3       3  5.455321   
3     4   234   MANDI    16    M      16    Z      Z     5       5  5.455321   
4     5   244  T20071    25    T      25    Z      Z     6       6  5.497168   

     col8_8  
0  3.526361  
1  1.386294  
2  5.455321  
3  5.455321  
4  5.497168

# Numpy - Numeric Python
**Friday, 9 December 2022**           
Actully derived from Matlab

In [16]:
import numpy as np

very usefull in Machine learning a lot useful - text,image,mp4 file, NLP everywhere           
system doesnt understand image, not pixel not color.

Pandas convert data that it can use in machine learning 

* array is equivalent to list.       
* system always understand array and matrix.         
array is a data type.

In [17]:
l = [1,2,3,5,'sharad']
type(l)

list

In [18]:
a = np.array(l)
a

array(['1', '2', '3', '5', 'sharad'], dtype='<U11')

\<U11 - datatype inside datatype 

In [19]:
type(a)

numpy.ndarray

ndarray - n dimensional array 

In [20]:
np.array([3,4,5,6,5])

array([3, 4, 5, 6, 5])

In [21]:
np.array([3,4,5,6,5.0])

array([3., 4., 5., 6., 5.])

called typecasting

In [22]:
a1 = np.array([[1,3],[2,4]])
a1

array([[1, 3],
       [2, 4]])

In [23]:
type(a1)

numpy.ndarray

In [24]:
a1[1] # first row

array([2, 4])

In [25]:
a1[1][1]

4

In [26]:
a1[0]

array([1, 3])

In [27]:
a = np.array([3,4,5,6,5.0])
a[1]

4.0

In [28]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
np.array([1,2,3,4,5],ndmin=0)

array([1, 2, 3, 4, 5])

In [30]:
np.array([1,2,3,4,5],ndmin=1)

array([1, 2, 3, 4, 5])

In [31]:
np.array([1,2,3,4,5],ndmin=2)

array([[1, 2, 3, 4, 5]])

changed the optput

In [32]:
np.array([1,2,3,4,5],ndmin=3)

array([[[1, 2, 3, 4, 5]]])

In [33]:
np.array([1,2,3,4,5],ndmin=4)

array([[[[1, 2, 3, 4, 5]]]])

extract 1 

In [34]:
a2 = np.array([1,2,3,4,5],ndmin=4)
a2[0]

array([[[1, 2, 3, 4, 5]]])

In [35]:
a2[0][0]

array([[1, 2, 3, 4, 5]])

In [36]:
a2[0][0][0]

array([1, 2, 3, 4, 5])

In [37]:
a2[0][0][0][0]

1

In [38]:
a1

array([[1, 3],
       [2, 4]])

In [39]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [40]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [41]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

different output           
* ```matrix([[1, 2, 3, 4, 5]])``` gives 2 dim. data bydefault two bracket 

In [42]:
a = [1, 2, 3, 4, 5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [43]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [44]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [45]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [46]:
np.fromfunction(lambda i,j : i ==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

* i row
* j column

In [47]:
np.fromfunction(lambda i,j : i*j , (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [48]:
np.fromfunction(lambda i,j : i*j , (4,4),dtype= int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

matrix is subclass of array 

In [49]:
np.mat(np.fromfunction(lambda i,j : i*j , (4,4),dtype= int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [50]:
np.mat(np.fromfunction(lambda i,j,k : i*j*k , (4,4),dtype= int))

TypeError: <lambda>() missing 1 required positional argument: 'k'

In [51]:
np.fromfunction(lambda i,j,k : i*j*k , (3,3,3),dtype= int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [52]:
np.fromfunction(lambda i,j,k : i*j*k , (3,3,2),dtype= int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

```(3,3,2)``` - looking for 3 mat of dimensions (3,2)
* (3z,3x,2y)

In [53]:
np.fromfunction(lambda i,j,k,l : i*j*k*l , (4,3,2,2),dtype= int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

no visualization

we have (2,2) array in a bundle of 3 and there are 4 

In [54]:
a = np.fromfunction(lambda i,j,k : i*j*k , (4,3,2),dtype= int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [55]:
a.ndim # number of dimensions

3

In [56]:
a.size # (24 elelment )

24

In [57]:
a.shape # dimensions in x,y,z

(4, 3, 2)

In [58]:
a.dtype

dtype('int32')

### 100 rows and 2000 column creation

In [59]:
# convert numpy in dataframe
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [60]:
a = (np.fromfunction(lambda i,j : i*j , (4,4),dtype= int))
a

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [61]:
pd.DataFrame(a)

0  1  2  3
0  0  0  0  0
1  0  1  2  3
2  0  2  4  6
3  0  3  6  9

In [62]:
a = (np.fromfunction(lambda i,j : i*j , (400,40),dtype= int))
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    37,    38,    39],
       [    0,     2,     4, ...,    74,    76,    78],
       ...,
       [    0,   397,   794, ..., 14689, 15086, 15483],
       [    0,   398,   796, ..., 14726, 15124, 15522],
       [    0,   399,   798, ..., 14763, 15162, 15561]])

In [63]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     30  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     30   
2     0    2    4     6     8    10    12    14    16    18  ...     60   
3     0    3    6     9    12    15    18    21    24    27  ...     90   
4     0    4    8    12    16    20    24    28    32    36  ...    120   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  11850   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  11880   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  11910   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  11940   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  11970   

        31     32     33     34     35     36     37     38     39  
0        0      0      0      0      0      0      0      0      0  
1       31     32     33     34     35     36     37     38     39  
2       62     64     66     68     70     72     74     76     78  
3       93     96     99    102    105    108    111    114    117  
4      124    128    132    136    140    144    148    152    156  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  12245  12640  13035  13430  13825  14220  14615  15010  15405  
396  12276  12672  13068  13464  13860  14256  14652  15048  15444  
397  12307  12704  13101  13498  13895  14292  14689  15086  15483  
398  12338  12736  13134  13532  13930  14328  14726  15124  15522  
399  12369  12768  13167  13566  13965  14364  14763  15162  15561  

[400 rows x 40 columns]

In [64]:
np.random.rand(10,4)

array([[0.68147004, 0.93308739, 0.30923163, 0.00597018],
       [0.09098419, 0.43723134, 0.83034647, 0.81170822],
       [0.82441086, 0.179402  , 0.56950627, 0.8522994 ],
       [0.0185617 , 0.34394025, 0.25695103, 0.40060939],
       [0.96595321, 0.0898198 , 0.71802305, 0.21613631],
       [0.67750903, 0.60223886, 0.06131197, 0.2467421 ],
       [0.30025807, 0.12303313, 0.1327102 , 0.62260912],
       [0.99137622, 0.5397762 , 0.54848128, 0.49589566],
       [0.79185558, 0.54944835, 0.63228665, 0.84914742],
       [0.70821227, 0.53378157, 0.20503479, 0.82826537]])

In [65]:
np.random.randint(4,1009098)

478036

In [66]:
np.random.randn(4,5) 
# it will give with normal distribution means avg will be zero

array([[ 0.41806206,  0.6297965 ,  1.64875334, -1.23291115,  0.35722922],
       [-0.02367209, -0.12750113, -0.87240899,  1.73155118, -0.59364635],
       [ 0.41012226,  0.73407755,  0.74008752, -0.19009601, -0.21722001],
       [ 1.44210634,  1.30934344, -1.74076017, -2.22947508, -0.71732438]])

In [67]:
pd.DataFrame(np.random.randn(4,5)) # SD = 1

0         1         2         3         4
0 -2.318423  0.292935  0.602288 -0.327024  2.774686
1  0.177160  0.856545  0.644332  1.292134  1.803339
2  0.252027  1.660402 -0.301659  0.748834 -0.735518
3  0.466757 -0.691433  0.281942 -0.384234  0.814230

###### change the dimension of array

In [68]:
a = np.fromfunction(lambda i,j,k : i*j*k , (4,3,2),dtype= int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [69]:
a.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [70]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

Work only when multiplication will be equal to 24 like (12,2) 1,24 - 24,1 - 6,4

In [71]:
# in 4D 
a.reshape(6,2,1,2) 

array([[[[0, 0]],

        [[0, 0]]],


       [[[0, 0]],

        [[0, 0]]],


       [[[0, 1]],

        [[0, 2]]],


       [[[0, 0]],

        [[0, 2]]],


       [[[0, 4]],

        [[0, 0]]],


       [[[0, 3]],

        [[0, 6]]]])

color is combination of RGB value

In [72]:
a.reshape(4,-1) # -1 take rest of dim means 6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [73]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [74]:
a.reshape(6,-14352345435) # any -ve number going to meke the same sence

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [75]:
a.reshape(6,2,-14352345435)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2]],

       [[0, 4],
        [0, 0]],

       [[0, 3],
        [0, 6]]])

In [84]:
list(range(4,10,2))

[4, 6, 8]

In [85]:
list(range(4,10,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [86]:
np.arange(4,10,0.2) # possible in np

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [87]:
list(range(4,10.5,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [89]:
a1 = np.arange(4,10.5,0.2)
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [91]:
a1[1:5]

array([4.2, 4.4, 4.6, 4.8])

In [93]:
arr = np.random.rand(4,5)
arr

array([[0.37182606, 0.00575741, 0.21317524, 0.78222294, 0.85642389],
       [0.24819123, 0.44555746, 0.31558467, 0.32690648, 0.9758729 ],
       [0.17145127, 0.15077136, 0.54233166, 0.2746969 , 0.51366845],
       [0.47165771, 0.78866181, 0.9446599 , 0.74154376, 0.43399638]])

In [94]:
# extract all the data which have value greater than 5
arr > 0.5

array([[False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False, False,  True, False,  True],
       [False,  True,  True,  True, False]])

In [95]:
arr[arr>0.5]

array([0.78222294, 0.85642389, 0.9758729 , 0.54233166, 0.51366845,
       0.78866181, 0.9446599 , 0.74154376])

In [101]:
arr[[1,2],[2]]

array([0.31558467, 0.54233166])

In [102]:
arr = np.random.rand(8,5)
arr

array([[0.24951373, 0.58525314, 0.1300555 , 0.21038853, 0.35732401],
       [0.90726175, 0.39461908, 0.24672774, 0.5799499 , 0.29731244],
       [0.16667858, 0.01021763, 0.71641134, 0.07574934, 0.53124351],
       [0.87725746, 0.96707754, 0.61965462, 0.06712569, 0.81127992],
       [0.94815265, 0.42318695, 0.40372958, 0.12319947, 0.91476344],
       [0.12262627, 0.13227214, 0.00760738, 0.72742788, 0.74639088],
       [0.08204905, 0.58981355, 0.74478429, 0.4700461 , 0.80946917],
       [0.40364128, 0.3428742 , 0.15079488, 0.24265676, 0.45880471]])

In [105]:
arr[1:8,0:3]

array([[0.90726175, 0.39461908, 0.24672774],
       [0.16667858, 0.01021763, 0.71641134],
       [0.87725746, 0.96707754, 0.61965462],
       [0.94815265, 0.42318695, 0.40372958],
       [0.12262627, 0.13227214, 0.00760738],
       [0.08204905, 0.58981355, 0.74478429],
       [0.40364128, 0.3428742 , 0.15079488]])

In [108]:
a2 = arr[1:8,[0,1,2]]
a2

array([[0.90726175, 0.39461908, 0.24672774],
       [0.16667858, 0.01021763, 0.71641134],
       [0.87725746, 0.96707754, 0.61965462],
       [0.94815265, 0.42318695, 0.40372958],
       [0.12262627, 0.13227214, 0.00760738],
       [0.08204905, 0.58981355, 0.74478429],
       [0.40364128, 0.3428742 , 0.15079488]])

In [110]:
a2[0][0]

0.9072617456400844

In [111]:
a2[0][0] = 945

In [112]:
a2

array([[9.45000000e+02, 3.94619084e-01, 2.46727743e-01],
       [1.66678584e-01, 1.02176282e-02, 7.16411336e-01],
       [8.77257457e-01, 9.67077536e-01, 6.19654616e-01],
       [9.48152651e-01, 4.23186950e-01, 4.03729575e-01],
       [1.22626274e-01, 1.32272144e-01, 7.60738287e-03],
       [8.20490529e-02, 5.89813545e-01, 7.44784285e-01],
       [4.03641280e-01, 3.42874204e-01, 1.50794882e-01]])

In [113]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
a

array([[1, 2],
       [3, 4]])

In [114]:
b

array([[2, 3],
       [4, 5]])

In [115]:
a*b # element wise multiplication

array([[ 2,  6],
       [12, 20]])

In [118]:
m = a@b # matrix multiplication
m

array([[10, 13],
       [22, 29]])

> matrix multiplication going to use alot in deep learning

In [119]:
 m/0

C:\Users\HP\AppData\Local\Temp\ipykernel_7580\2289511133.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [120]:
m/2

array([[ 5. ,  6.5],
       [11. , 14.5]])