# Numpy Method 
**Tuesday, 13 December 2022**
> 1. Matrix is a sub part of array, array can be any dim but mat will be in 2D dim only.
> 1. Numpy derived from Matlab.

In [1]:
import numpy as np
l = [1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

> Deep learning and computer vision where below method going to use. 

In [2]:
np.zeros(5)  # create 1d array means 1 single row

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

> zeros used for nullify the RGB value 

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

> not beyond ones and zeros is available

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [10]:
np.empty((4,5)) # rondom value but mag will be very small or close to zero e-312

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.11260144e-306, 6.89812281e-307],
       [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307]])

In [11]:
np.empty((2,4,5))

array([[[nan, nan, nan,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [12]:
np.linspace(2,6) # Return evenly spaced numbers over a specified interval.
# it will generate only single dim array 

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [13]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [14]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [15]:
np.linspace(2,10,20).reshape(5,4)
# it will take upper bound also

array([[ 2.        ,  2.42105263,  2.84210526,  3.26315789],
       [ 3.68421053,  4.10526316,  4.52631579,  4.94736842],
       [ 5.36842105,  5.78947368,  6.21052632,  6.63157895],
       [ 7.05263158,  7.47368421,  7.89473684,  8.31578947],
       [ 8.73684211,  9.15789474,  9.57894737, 10.        ]])

In [16]:
np.linspace(2,20,10 , endpoint= False)
# Now there will be 10 element but last ele will not be there in output

array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2])

In [17]:
np.linspace(2,20,10 , endpoint= False).reshape(5,2)

array([[ 2. ,  3.8],
       [ 5.6,  7.4],
       [ 9.2, 11. ],
       [12.8, 14.6],
       [16.4, 18.2]])

In [18]:
np.linspace(2,20,10 , endpoint= False,retstep=True)

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2]), 1.8)

> 1.8 is step size will also visible

In [19]:
np.linspace(2,20,10 , endpoint= False,retstep=True)

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2]), 1.8)

In [20]:
np.logspace(1,10,10)  # same as linspace but in this function log value will return

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [21]:
np.logspace(1,10,10, base = 10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [22]:
np.logspace(1,10,10, base = 2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [23]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [24]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
a = a.reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
a.max() #return max value not index

15

In [27]:
b = np.arange(4,20).reshape(4,4)
b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
b.max() # it will give max number 

19

In [29]:
c = np.arange(4,40).reshape(3,6,2)
c

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [30]:
c.max()

39

In [31]:
c.max(axis = 1) # column wise serchingg max

array([[14, 15],
       [26, 27],
       [38, 39]])

In [32]:
c.max(axis = 0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [33]:
d = np.arange(4,40).reshape(6,6)
d

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [34]:
d.max()

39

In [35]:
d.max(axis = 0) # == 0 row
# 4,10 .....34 representing row parsing so axis = 0 show row

array([34, 35, 36, 37, 38, 39])

> opposite of understand that we have 

In [36]:
d.max(axis = 1)  # == 1 column wise max
# 4,  5,  6,  7,  8,  9 representing column parsing so axis == 1 is column

array([ 9, 15, 21, 27, 33, 39])

In [37]:
d

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [38]:
d**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [39]:
pow(d,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [40]:
pow(d,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [41]:
pow(d,10)

array([[    1048576,     9765625,    60466176,   282475249,  1073741824,
         -808182895],
       [ 1410065408,   167620825,  1787822080,   419538377,  1491846144,
         1124772961],
       [          0,  1654238625,  1349403648, -2147040887,   797966336,
        -1771999463],
       [ -154967040,  1551643729,  1073741824,  1977800241,   110568448,
        -1010140999],
       [-1357905920, -1993212183,   716276736, -1796951359,           0,
        -2057521855],
       [ 1723237376,  1528444521, -1190133760,  -882641607,   453387264,
          -49739855]], dtype=int32)

In [42]:
d

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [43]:
e = np.array([9,3,1,2,3,4])
e

array([9, 3, 1, 2, 3, 4])

In [44]:
d + e  # broadcasting

array([[13,  8,  7,  9, 11, 13],
       [19, 14, 13, 15, 17, 19],
       [25, 20, 19, 21, 23, 25],
       [31, 26, 25, 27, 29, 31],
       [37, 32, 31, 33, 35, 37],
       [43, 38, 37, 39, 41, 43]])

In [45]:
 d + 10 

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [46]:
f = np.array([2,3,1,2,3])
f

array([2, 3, 1, 2, 3])

In [47]:
d + f

ValueError: operands could not be broadcast together with shapes (6,6) (5,) 

In [48]:
e = e.T

In [49]:
d + e # column wise broadcasting

array([[13,  8,  7,  9, 11, 13],
       [19, 14, 13, 15, 17, 19],
       [25, 20, 19, 21, 23, 25],
       [31, 26, 25, 27, 29, 31],
       [37, 32, 31, 33, 35, 37],
       [43, 38, 37, 39, 41, 43]])

> e is 1D so for transpose e needs to convert into 2d

In [50]:
e = e.reshape(1,-1)
e

array([[9, 3, 1, 2, 3, 4]])

> now e convert into 2d

In [51]:
g = e.T
g

array([[9],
       [3],
       [1],
       [2],
       [3],
       [4]])

In [53]:
d

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [52]:
g + d

array([[13, 14, 15, 16, 17, 18],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [54]:
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [56]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [59]:
np.log10(a)

C:\Users\HP\AppData\Local\Temp\ipykernel_7716\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [60]:
x = np.array([1,2,3])
y = x # swallow copy
y 

array([1, 2, 3])

In [61]:
x

array([1, 2, 3])

In [62]:
z = np.copy(x) # deep copy

In [63]:
z

array([1, 2, 3])

In [64]:
y

array([1, 2, 3])

> deep copy and swallow copy

In [67]:
x == y 

array([ True,  True,  True])

In [68]:
id(x) == id(y) # anytype of change in x will affect on y

True

In [70]:
id(z) == id(x)

False

In [71]:
x[0] = 100

In [72]:
x

array([100,   2,   3])

In [73]:
y

array([100,   2,   3])

In [74]:
z # z will not change 

array([1, 2, 3])

> id show memory location,memory address

> Return the identity of an object.

> This is guaranteed to be unique among simultaneously existing objects.

In [80]:
id(x) 

3043883111696

In [81]:
id(y)

3043883111696

In [87]:
id(y[0])

3043885602704

In [88]:
id(x[0])

3043885602064

In [101]:
id(x[0]) == id(y[0])

True

> not similar identity

In [83]:
id(z)

3043882042928

In [92]:
sharad = np.array([34,3443])
df = sharad

In [93]:
id(df)

3043882042736

In [95]:
id(sharad)

3043882042736

In [103]:
id(sharad) == id(df)

True

In [98]:
id(sharad[0])

3043885604272

In [102]:
id(df[0])

3043883999600

> element wise id is different

In [100]:
id(sharad[0]) == id(sharad[0])

True

> How, ouptput is diffenrent but here is True

> Hw - Try to find out why ?  actual m

In [105]:
# Hint
c = 'IIT'
id(c) == id(sharad)

False