# Programming Assignment_13
**Tuesday, 27 December 2022**             
[sharadpardhe08@gmail.com](link)

### **Question 1: Write a program that calculates and prints the value according to the given formula:**

> Q = ```Square root of [(2 * C * D)/H]```       
Following are the fixed values of C and H:         
```C``` is 50. ```H``` is 30.         
```D``` is the variable whose values should be input to your program in a comma-separated sequence.      

**Example**

>Let us assume the following comma separated input sequence is given to the program:      
100,150,180       
The output of the program should be:         
18,22,24

In [3]:
# Importing neccesary module 
import math 

# given
C = 50 
H = 30

# assume value of 
D = [100,200,30]

# define empty list for storring element
res = []

for i in D:
    Q = math.sqrt((2 * C * i)/H)
    res.append(Q)

print('The results of Q are:', res)

The results of Q are: [18.257418583505537, 25.81988897471611, 10.0]


### **Question 2:Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.**

> **Note:** i=0,1......, X-1;            
j=0,1,.......,Y-1.

**Example**

> Suppose the following inputs are given to the program: ```3,5```       
Then, the output of the program should be:       
[[0, 0, 0, 0, 0],      
[0, 1, 2, 3, 4],       
[0, 2, 4, 6, 8]]         


In [9]:
import numpy as np 
def matrix_creation(X,Y):
    '''program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.'''
    
    mat  = np.zeros((X,Y))
    
    for i in range(len(mat)): # iterate through each row
        for j in range(len(mat[0])): # iterate through each column 
            mat[i][j] = int(i*j)     # storing the ele in mat
    
    new_mat = mat.astype(int)   # converting float to int 
    
    return new_mat
                    
print(matrix_creation(4,5))

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]]


### Question 3: Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

>Suppose the following input is supplied to the program:  ```without,hello,bag,world```          
Then, the output should be: ```bag,hello,without,world```

In [15]:
words = input('Please enter comma separated sequence of words: ')
lst_word = words.split(',')
sort_list = sorted(lst_word)
(',').join(sort_list)

Please enter comma separated sequence of words: without,hello,bag,world


'bag,hello,without,world'

### Question 4: Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

> Suppose the following input is supplied to the program:```hello world and practice makes perfect and hello world again```    
Then, the output should be:```again and hello makes perfect practice world```


In [17]:
words = input('Please enter whitespace separated sequence of words: ')
lst_word = words.split(' ')
word_set = set(lst_word)
sort_list = sorted(word_set)
(' ').join(sort_list)

Please enter whitespace separated sequence of words: hello world and practice makes perfect and hello world again


'again and hello makes perfect practice world'

### Question 5: Write a program that accepts a sentence and calculate the number of letters and digits.

> Suppose the following input is supplied to the program: ```hello world! 123```  

>Then, the output should be:        
LETTERS 10      
DIGITS 3     

In [4]:
sentence = input('Enter the sentence: ')

Letters = ''
Digits = ''

for i in sentence:
    if i.isdigit():
        Digits += i
    elif i.isalpha():
        Letters += i
        
print(f'Letters - {len(Letters)}\nDigits - {len(Digits)}')

Enter the sentence: hello world! 123
Letters - 10
Digits - 3


### Question 6: A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

> Following are the criteria for checking the password:       
> 1. At least 1 letter between [a-z]
> 1. At least 1 number between [0-9]
> 1. At least 1 letter between [A-Z]
> 1. At least 1 character from [$#@]   
> 1. Minimum length of transaction password: 6
> 1. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

**Example**

> If the following passwords are given as input to the program:```ABd1234@1,a F1#,2w3E*,2We3345```      
Then, the output of the program should be:```ABd1234@1```


In [11]:
import re 

password = input('Enter the password: ').split(',')
valid = []

for i in password:
    
    if len(i) < 6 or len(i)>12:
        continue
    elif not re.search(r'[a-z]',i):
        continue
    elif not re.search(r'[A-Z]',i):
        continue
    elif not re.search(r'[0-9]',i):
        continue
    elif not re.search(r'[$#@]',i):
        continue
    else:
        valid.append(i)
        
print('The valid password is :', str(valid))

Enter the password: ABd1234@1,a F1#,2w3E*,2We3345
The valid password is : ['ABd1234@1']
