# Programming_Assignment_007
[sharadpardhe08@gmail.com](link)

**1.	Write a Python Program to find sum of array?              
Answer-**
> 1st method

In [1]:
# using loop
l = [1,2,3,4,5,6]
sum = 0
for i in l:
    sum = sum + i
sum

21

> using numpy

In [2]:
import numpy as np
l = [1,2,3,4,5,6]
np.sum(l) #summation of all element

21

In [3]:
import numpy as np
arr = np.array([[1,2,4,5],[2,3,4,5],[1,2,3,100]])
arr

array([[  1,   2,   4,   5],
       [  2,   3,   4,   5],
       [  1,   2,   3, 100]])

In [4]:
np.sum(arr,axis = 1) # column wise summation

array([ 12,  14, 106])

In [5]:
np.sum(arr,axis = 0) # row wise summation

array([  4,   7,  11, 110])

**2.	Write a Python Program to find largest element in an array?                  
Answer-**
> first method

In [6]:
l = [2,2,433,5,235,35,23]
max = l[0]
for i in range(1,len(l)):
    if l[i] > max:
        max = l[i]
max

433

> using numpy

In [7]:
np.max(l)

433

**3.	Write a Python Program for array rotation?            
Answer-**

In [8]:
rotation = int(input('Rotation by how many place: '))
arr = [2,2,433,5,235,35,23]
temp = []
i = 0 

while i < rotation:
    temp.append(arr[i])
    i = i+1
    
i = 0
while rotation < len(arr):
    arr[i] = arr[rotation]
    i = i+1
    rotation = rotation + 1
    
arr = arr[:i] + temp
print(f'Array after rotation: {arr}' )

Rotation by how many place: 4
Array after rotation: [235, 35, 23, 2, 2, 433, 5]


**4.	Write a Python Program to Split the array and add the first part to the end?            
Answer-**

In [9]:
arr = [2,2,433,5,235,35,23]
print(f'original arry: {arr}')

part = ((len(arr))//2)

part_1 = arr[:part+1]
print(f'part_1 {part_1}')

part_2 = arr[part+1:]
print(f'part_2 {part_2}')

new_arr = part_2 + part_1
print(f'New array after split {new_arr}')

original arry: [2, 2, 433, 5, 235, 35, 23]
part_1 [2, 2, 433, 5]
part_2 [235, 35, 23]
New array after split [235, 35, 23, 2, 2, 433, 5]


**5.	Write a Python Program to check if given array is Monotonic?              
Answer-**          
An array is monotonic if it is either monotone increasing or monotone decreasing. An array A is monotone increasing if for all i <= j, A[i] <= A[j]. 

In [10]:
def check_monotonic(arr):
    x, y = [], []
    x.extend(arr)
    y.extend(arr)
    x.sort()
    y.sort(reverse=True)
    if(x == arr or y == arr):
        return True
    return False
 
arr = [10, 8, 6, 5,4,3,2]
print(check_monotonic(arr))

True
