# Programming_Assignment_008
**Sunday, 18 December 2022**       
[sharadpardhe08@gmail.com](link)

**1. Write a Python Program to Add Two Matrices?                
Answer-**

In [1]:
# solution for 1d array 
arr1 = [1,2,3,4,5,6]
arr2 = [7,8,9,10,11,12]
arr_zip = list(zip(arr1,arr2))
arr_sum = []
for i,j in arr_zip:
    arr_sum.append(i+j)
arr_sum

[8, 10, 12, 14, 16, 18]

In [2]:
# solution for 2d array 
A = [[1,2,4],
    [4,23,52],
    [8,9,35]]

B = [[3,6,9],
    [12,15,18],
    [21,24,27]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(result)): # loop over row
    for j in range(len(result[0])): #loop over column
        result[i][j] = A[i][j] + B[i][j]
        
print(result,'\n')
for i in result:
    print(i)

[[4, 8, 13], [16, 38, 70], [29, 33, 62]] 

[4, 8, 13]
[16, 38, 70]
[29, 33, 62]


In [3]:
# by numpy 
import numpy as np
arr1 = np.array(A)  # converting A in numpy array
arr2 = np.array(B)  # converting B in numpy array
arr1 + arr2         # sum of two array

array([[ 4,  8, 13],
       [16, 38, 70],
       [29, 33, 62]])

**2. Write a Python Program to Multiply Two Matrices?                   
Answer-**

In [4]:
# using numpy
arr1@arr2

array([[ 111,  132,  153],
       [1380, 1617, 1854],
       [ 867, 1023, 1179]])

In [5]:
# using programme
X = [[1,2,4],
    [4,23,52],
    [8,9,35]]

Y = [[3,6,9],
    [12,15,18],
    [21,24,27]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)): # iterate through row of X
    for j in range(len(Y[0])): # iterate through column of Y
        for k in range(len(Y)): # iterate through row of Y
            result[i][j] = result[i][j] + (X[i][k] * Y[k][j])
     

for r in result:
    print(r)


[111, 132, 153]
[1380, 1617, 1854]
[867, 1023, 1179]


**3. Write a Python Program to Transpose a Matrix?              
Answer-**
> using numpy

In [6]:
arr1

array([[ 1,  2,  4],
       [ 4, 23, 52],
       [ 8,  9, 35]])

In [7]:
arr1.T

array([[ 1,  4,  8],
       [ 2, 23,  9],
       [ 4, 52, 35]])

> using programme

In [8]:
X = [[1,2,4],
    [4,23,52],
    [8,9,35]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)): # iterate through row
    for j in range(len(X[0])): # iterate through column
        result[i][j] = X[j][i]
for r in result:
    print(r)

[1, 4, 8]
[2, 23, 9]
[4, 52, 35]


**4. Write a Python Program to Sort Words in Alphabetic Order?              
Answer-**

In [9]:
my_string = 'My name is sharad and I am from India' # input('Enter string: ') 
word_list = [word.lower() for word in my_string.split()]
word_list.sort()
print('words are in alphabatic order: \n',)
for word in word_list:
    print(word)

words are in alphabatic order: 

am
and
from
i
india
is
my
name
sharad


**5. Write a Python Program to Remove Punctuation From a String?              
Answer-**

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_string = ''' Hello!, My name is sharad, & I am from India (~BHARAT) --- []<>''' # input('Enter string: ')

string_no_punc = ''

for i in my_string:
    if i not in punctuations:
        string_no_punc += i
        
string_no_punc

' Hello My name is sharad  I am from India BHARAT  '